### ISSUE TITLE
Error in vt normalize on case mismatch to reference causes FreebayesJointCallV2 to fail

### ISSUE THREAD

**Issue by tonydisera** [iobio/iobio-gru-backend#110]
We need to add the -n flag so that these mismatches don't cause failures. There are regions of the genome with low confidence that are indicated with lowercase nucleotide base letters. When vt normalize encounters a variant in one of these regions, it was failing. 
To be consistent with other services, we are replacing vt normalize with bcftool normalize, adding the -m flag.
`bcftools norm -m - -w 10000 -f $refFastaFile `

**Comment by anderspitman** [comment]
Merged
