### ISSUE TITLE
Gemdrive data download fails, install_singularity.sh link broken

### ISSUE THREAD

**Issue by jdy4389** [iobio/iobio-gru-backend#92]
When trying to populate the Data folder with the download script, it always times out.
```
./download.py --gru-version 1.6.0 --out-dir data
Timed out retrieving https://gemdrive.iobio.io/gemdrive/index/gru-1.6.0/tree.json?depth=0
Traceback (most recent call last):
  File "./download.py", line 198, in <module>
    client.sync(url, args.out_dir)
  File "./download.py", line 29, in sync
    self.traverse(gemdrive_url, fs_dir, None)
  File "./download.py", line 48, in traverse
    res = request.urlopen(gem_url, timeout=5)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```
I think the following error on the gemdrive is related, it looks like there may be an issue on the backend due to the large amount of files in the tree that get queried:
`open /mnt/gru-1.6.0/data/md5_reference_cache/0d/63: too many open files`

Also, the link for version 3.5.3 of singularity that is attempted to get downloaded with the install_singularity script fails and it downloads something that isn't a real .tar.gz file. I think something was forked, or something with that project changed, and I had to go and find version 3.5.3 elsewhere but it ended up working when I installed it manually.

**Comment by anderspitman** [comment]
Hey @jdy4389, thanks for the report. Unfortunately some of the docs and scripts are pretty out of date. We don't have a lot of people self-hosting the backend. I can probably help you get it working though. Are you running on AWS by chance? The easiest way to download the data directory is by copying our EC2 snapshot. If not, I can provide you with an rsync endpoint that is more reliable than the GemDrive one.

Any details you can provide on your setup would be helpful as well.

**Comment by jdy4389** [comment]
Thanks, not using AWS at the moment unfortunately, I just wanted to try getting it running on a local server to see if it would be feasible in alleviating some network issues on my end. Can I try copying with rsync?

**Comment by anderspitman** [comment]
Sure thing. This should do it:

`rsync -av rsync://data.iobio.io:9009/gru/gru-1.6.0/ gru-1.6.0/`

What iobio apps are you wanting to use with it?

**Comment by jdy4389** [comment]
> Sure thing. This should do it:
> 
> `rsync -av rsync://data.iobio.io:9009/gru/gru-1.6.0/ gru-1.6.0/`
> 
> What iobio apps are you wanting to use with it?

Just gene.iobio

**Comment by anderspitman** [comment]
@jdy4389 any luck with that download? Once you have the data directory, I can help you get gene.iobio built.

**Comment by jdy4389** [comment]
> @jdy4389 any luck with that download? Once you have the data directory, I can help you get gene.iobio built.

Yeah, thanks for the link, I got the download and got the backend and gene.iobio running somewhat, where they were able to communicate together after changing some of the variables in gene.iobio to point to the localhost instead of the real iobio backend server. I could get it to load gene data from vcf/cram and it looked like some things were working right, like how it would get the header data from the file and show estimated coverage over the gene, but it wouldn't show any variants. I think it might be due to the way I set it up with the tools and because I was following the simple deployment guide and not using docker at first so I'm probably going to start over.

For the dockerfile, is it as simple as setting up the docker container from prod (in my case I had to uncomment line #28 for it to work) and running run_local.sh or is there additional set up required for things like compiling the tools and using singularity containers?

And for the data, since I have it on the host and not in the docker container, I'm assuming I can just mount that to where the backend expects it in the container?

**Comment by anderspitman** [comment]
Hey @jdy4389, I lost track of this issue, sorry. Did you end up with a satisfactory setup, or still need some help?

**Comment by jdy4389** [comment]
> Hey @jdy4389, I lost track of this issue, sorry. Did you end up with a satisfactory setup, or still need some help?

No it works now, thanks for your help

**Comment by anderspitman** [comment]
No problem, feel free to let us know if you run into more issues.
